apiVersion: crd.dismas.org/v1
kind: Job
metadata:
  labels:
    app.kubernetes.io/name: error-args
    app.kubernetes.io/instance: error-args
    app.kubernetes.io/part-of: dismas
    app.kubernetes.io/managed-by: helm
    app.kubernetes.io/created-by: dismas
  name: error-args
  namespace: dismas-system
spec:
  command: "ls"
  args: ["--this is a wrong args"]
