apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: dismas-controller
  namespace: dismas-system
spec:
  selector:
    matchLabels:
      name: dismas-controller
  template:
    metadata:
      labels:
        name: dismas-controller
    spec:
      containers:
      - name: dismas-controller
        image: esphe/dismas:build
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
        volumeMounts:
        - name: varlog
          mountPath: /var/log
      terminationGracePeriodSeconds: 30
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
